name: Dockerized Tests & Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wdio-project .

      - name: Run WebdriverIO tests in Docker (retry up to 10×)
        run: |
          max_retries=10
          count=0

          until [ $count -gt $max_retries ]; do
            echo "→ Test attempt #$((count+1))"
            docker run --rm \
              -v ${{ github.workspace }}:/app \
              -v /app/node_modules \
              wdio-project \
              npm run test:headless && break

            count=$((count+1))
            echo "✖ Tests failed on attempt #$count."
            if [ $count -le $max_retries ]; then
              echo "→ Retrying in 5s…"
              sleep 5
            fi
          done

          if [ $count -gt $max_retries ]; then
            echo "✖ All $((max_retries+1)) attempts failed."
            exit 1
          fi

      - name: Generate Allure Report in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v /app/node_modules \
            wdio-project \
            npm run allure:gen

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          commit_message: "Deploy Allure report"