name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO Tests (10 retries max)
        run: |
          max_retries=10
          count=0

          until [ $count -gt $max_retries ]
          do
            echo "→ Test attempt #$((count+1))"
            npm run test:chrome && break
            count=$((count+1))
            echo "✖ Tests failed on attempt #$count."
            if [ $count -le $max_retries ]; then
              echo "→ Retrying tests..."
              # optional: sleep 5
            fi
          done

          if [ $count -gt $max_retries ]; then
            echo "✖ All $((max_retries+1)) attempts failed."
            exit 1
          fi

      - name: Generate Allure Report
        run: npm run allure:gen

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          commit_message: "Deploy Allure report"